# Android
ANDROID_VERSION_NAME=0.1.0
ANDROID_VERSION_CODE=2

# iOS
IOS_VERSION_NAME=0.1.0
IOS_VERSION_CODE=1

# macOS
MACOS_VERSION_NAME=0.1.0
MACOS_VERSION_CODE=1

# Linux
LINUX_VERSION_NAME=0.1.0
LINUX_VERSION_CODE=1

# Windows
WINDOWS_VERSION_NAME=0.1.0
WINDOWS_VERSION_CODE=1
